# -*- coding: utf-8 -*-
"""normalizing afrimed qa 400 samples

Automatically generated by Colab.


import json
import os
import random
from datasets import load_dataset, concatenate_datasets

afrimedqa = load_dataset("intronhealth/afrimedqa_v2")

def normalize_medqa_file(filepath):
    """Normalize a MedQA JSONL file to common schema."""
    normalized = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            data = json.loads(line)
            options = data.get('options', {})

            # Convert options dict to list format with indices
            options_list = []
            for key in ['A', 'B', 'C', 'D', 'E']:
                if key in options:
                    options_list.append({
                        'idx': key,
                        'text': options[key]
                    })

            normalized.append({
                'question': data.get('question', ''),
                'options': options_list,
                'answer': data.get('answer', ''),
                'answer_idx': data.get('answer_idx', ''),
                'source': 'medqa',
                'meta_info': data.get('meta_info', '')
            })
    return normalized

def normalize_afrimedqa(dataset):
    """Normalize AfrimedQA dataset to common schema."""
    normalized = []
    for item in dataset:
        options_list = []
        answer_idx = None
        correct_answer = ''

        if item.get('answer_options'):
            # answer_options can be a JSON string or dict
            options_dict = item['answer_options']
            if isinstance(options_dict, str):
                try:
                    options_dict = json.loads(options_dict)
                except json.JSONDecodeError:
                    options_dict = None

            if options_dict and isinstance(options_dict, dict):
                # Convert option1, option2, etc. to A, B, C, etc.
                idx_map = {f'option{i}': chr(65+i-1) for i in range(1, 6)}  # option1->A, option2->B, etc.
                for opt_key, letter_idx in idx_map.items():
                    if opt_key in options_dict:
                        options_list.append({
                            'idx': letter_idx,
                            'text': options_dict[opt_key]
                        })

                # Find the correct answer index
                correct_answer = item.get('correct_answer', '')
                if correct_answer:
                    # Check if it's like "option1", "option2", etc. and map to text
                    if isinstance(correct_answer, str) and correct_answer.startswith('option'):
                        opt_nums = correct_answer.replace('option', '').split(',')
                        answer_idxs = []
                        answer_texts = []
                        for opt_num in opt_nums:
                            try:
                                opt_num_i = int(opt_num.strip())
                                letter_idx = chr(65+opt_num_i-1)  # option1->A, option2->B
                                answer_idxs.append(letter_idx)
                                answer_texts.append(options_dict.get(f'option{opt_num_i}', ''))
                            except Exception:
                                pass

                        if answer_idxs:
                            answer_idx = ','.join(answer_idxs) if len(answer_idxs) > 1 else answer_idxs[0]
                            correct_answer = ', '.join(answer_texts) if len(answer_texts) > 1 else answer_texts[0]
                    else:
                        # It's the actual answer text
                        for opt in options_list:
                            if opt['text'] == correct_answer:
                                answer_idx = opt['idx']
                                break

        normalized.append({
            'question': item.get('question', ''),
            'options': options_list,
            'answer': correct_answer if correct_answer else item.get('correct_answer', ''),
            'answer_idx': answer_idx,
            'source': 'afrimedqa',
            'sample_id': item.get('sample_id', ''),
            'split': item.get('split', ''),
            'gender': item.get('gender', ''),
            'country': item.get('country', ''),
            'specialty': item.get('specialty', ''),
            'tier': item.get('tier', ''),
            'question_type': item.get('question_type', '')
        })
    return normalized

def save_normalized(data, filepath):
    """Save normalized data to JSONL file."""
    out_dir = os.path.dirname(filepath)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
    print(f"Saved {len(data)} records to {filepath}")

# Normalize MedQA (US)
print("Processing MedQA US...")
medqa_us_files = {
    'test': 'data/raw/med-qa/questions/US/test.jsonl'
}

for split, filepath in medqa_us_files.items():
    if os.path.exists(filepath):

        data = normalize_medqa_file(filepath)

        N = 400
        seed = 42

        if len(data) < N:
            raise ValueError(f"Only {len(data)} MedQA items available; cannot sample {N}.")

        random.seed(seed)
        sampled_data = random.sample(data, N)

        save_normalized(sampled_data, f'data/processed/medqa_us_400.jsonl')

# Normalize AfrimedQA (MCQ-only, sample 400)
print("Processing AfrimedQA (MCQ only, random 400)...")
afrimedqa = load_dataset("intronhealth/afrimedqa_v2")

master_ds = afrimedqa["train"]

# Filter for BOTH the "test" split AND the "mcq" question type
mcq_ds = master_ds.filter(lambda x: x.get("split") == "test" and x.get("question_type") == "mcq")

# Randomly select 400
N = 400
seed = 42
if len(mcq_ds) < N:
    raise ValueError(f"Only {len(mcq_ds)} MCQ items available; cannot sample {N}.")

sample_ds = mcq_ds.shuffle(seed=seed).select(range(N))

# Normalize + save
normalized_mcq_400 = normalize_afrimedqa(sample_ds)
save_normalized(normalized_mcq_400, "data/processed/afrimedqa_mcq_400.jsonl")

print("Done!")
